name: Build test 2 (windows)

on:
  push:
    # branches-ignore:
    #   - '**'

env:
  cache-version: v1
  cache-version-uxp: v2

###############################################

jobs:
  build_win_x64:
    name: "Windows intel msvc"
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    # - name: Add msbuild to PATH
    #   uses: microsoft/setup-msbuild@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
      
    - name: Get env
      shell: cmd
      run: |
        echo on
        echo %VCToolsRedistDir%
        REM dir "%VCToolsRedistDir%"
        REM dir "%VCToolsRedistDir%x64"
        dir "%VCToolsRedistDir%x64\Microsoft.VC142.CRT"
        
        dir "%WindowsSdkDir%"
        dir "%WindowsSdkDir%\Redist"
        dir "%WindowsSdkDir%\Redist\%WindowsSDKLibVersion%"
        dir "%WindowsSdkDir%\Redist\%WindowsSDKLibVersion%\ucrt"
        dir "%WindowsSdkDir%\Redist\%WindowsSDKLibVersion%\ucrt\DLLs"
        dir "%WindowsSdkDir%\Redist\%WindowsSDKLibVersion%\ucrt\DLLs\x64"

    # - name: Get env (bash)
    #   shell: bash
    #   run: |
    #     set -eux
    #     # env
    #     echo $VCToolsRedistDir
    #     WIN32_REDIST_DIR="${VCToolsRedistDir}x64\\Microsoft.VC142.CRT"
    #     echo $WIN32_REDIST_DIR
        
    - uses: actions/cache@v4
      with:
        path: C:\mozilla-build\
        key: ${{ env.cache-version }}-mozbuild-${{ hashFiles('README.md') }}
        restore-keys: |
          ${{ env.cache-version }}-mozbuild-

    - uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}\uxp_gui\platform
        key: ${{ env.cache-version-uxp }}-uxp-${{ hashFiles('README.md') }}
        restore-keys: |
          ${{ env.cache-version-uxp }}-uxp-

    - name: Install prerequisite
      run: |
        $mozilladir = "c:\mozilla-build"

        if((Test-Path $mozilladir) -eq "True"){
          Write-Host "Cache exists"
          dir $mozilladir
        }else{
          Start-BitsTransfer -Source https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-3.4.exe -Destination ./MozillaBuildSetup.exe
          .\MozillaBuildSetup.exe /S | Out-Null
        }

        dir $mozilladir
        
    - name: Get repos dir
      shell: bash
      id: get-repos-dir
      run: |
        set -eux
        REPOS_DIR=$(echo '${{ github.workspace }}' | sed 's/\\/\//g')
        echo "repos-dir=$REPOS_DIR" >> $GITHUB_OUTPUT
        HOMEPATH_UX=$(echo "$HOMEPATH" | sed 's/\\/\//g')
        echo "home-dir=$HOMEDRIVE$HOMEPATH_UX" >> $GITHUB_OUTPUT
        # env

    - name: Install UXP
      shell: cmd
      run: |
        echo on
        cmd /c C:/mozilla-build/start-shell.bat ${{ steps.get-repos-dir.outputs.repos-dir }}/install_uxp.sh "%VCToolsRedistDir%x64\Microsoft.VC142.CRT" "%WindowsSdkDir%\Redist\%WindowsSDKLibVersion%\ucrt\DLLs\x64"

    # - name: Run mozilla build
    #   shell: cmd
    #   run: |
    #     echo on
    #     echo ${{ steps.get-repos-dir.outputs.repos-dir }}
    #     echo ${{ steps.get-repos-dir.outputs.home-dir }}
    #     cmd /c C:/mozilla-build/start-shell.bat ${{ steps.get-repos-dir.outputs.repos-dir }}/test_win1.sh ${{ steps.get-repos-dir.outputs.home-dir }}
